#include "MonolithEditorLevelMetadataActions.h"

#include "MonolithParamSchema.h"
#include "Components/StaticMeshComponent.h"
#include "Dom/JsonObject.h"
#include "Dom/JsonValue.h"
#include "Editor.h"
#include "Engine/Level.h"
#include "Engine/Light.h"
#include "Engine/StaticMesh.h"
#include "Engine/World.h"
#include "EngineUtils.h"
#include "GameFramework/Actor.h"
#include "HAL/FileManager.h"
#include "Materials/MaterialInterface.h"
#include "Misc/FileHelper.h"
#include "Misc/Paths.h"
#include "Misc/SecureHash.h"
#include "Serialization/JsonReader.h"
#include "Serialization/JsonSerializer.h"
#include "Serialization/JsonWriter.h"

namespace MonolithLevelMetadata
{
static TArray<TSharedPtr<FJsonValue>> VectorToJsonArray(const FVector& Vector)
{
	TArray<TSharedPtr<FJsonValue>> Array;
	Array.Add(MakeShared<FJsonValueNumber>(Vector.X));
	Array.Add(MakeShared<FJsonValueNumber>(Vector.Y));
	Array.Add(MakeShared<FJsonValueNumber>(Vector.Z));
	return Array;
}

static TSharedPtr<FJsonObject> TransformToJson(const FTransform& Transform)
{
	TSharedPtr<FJsonObject> Obj = MakeShared<FJsonObject>();
	const FRotator Rotation = Transform.Rotator();
	Obj->SetArrayField(TEXT("location"), VectorToJsonArray(Transform.GetLocation()));
	Obj->SetArrayField(TEXT("rotation"), VectorToJsonArray(FVector(Rotation.Pitch, Rotation.Yaw, Rotation.Roll)));
	Obj->SetArrayField(TEXT("scale"), VectorToJsonArray(Transform.GetScale3D()));
	return Obj;
}

static void AddStringSetAsArray(TSharedPtr<FJsonObject> Obj, const FString& FieldName, const TSet<FString>& Values)
{
	TArray<FString> Sorted = Values.Array();
	Sorted.Sort();

	TArray<TSharedPtr<FJsonValue>> Array;
	Array.Reserve(Sorted.Num());
	for (const FString& Value : Sorted)
	{
		Array.Add(MakeShared<FJsonValueString>(Value));
	}
	Obj->SetArrayField(FieldName, Array);
}
}

void FMonolithEditorLevelMetadataActions::RegisterActions()
{
	FMonolithToolRegistry& Registry = FMonolithToolRegistry::Get();

	Registry.RegisterAction(TEXT("level"), TEXT("preview_metadata_export"),
		TEXT("Traverse the current editor level and return metadata counts, warnings, and estimated output without writing files."),
		FMonolithActionHandler::CreateStatic(&HandlePreviewMetadataExport),
		FParamSchemaBuilder()
			.Optional(TEXT("include_foliage"), TEXT("bool"), TEXT("Include foliage-like actor classes"), TEXT("true"))
			.Optional(TEXT("max_actors"), TEXT("number"), TEXT("Maximum actors to include before reporting skipped rows"), TEXT("10000"))
			.Build());

	Registry.RegisterAction(TEXT("level"), TEXT("export_metadata"),
		TEXT("Write deterministic JSON level metadata and optional actor NDJSON under the project Saved directory."),
		FMonolithActionHandler::CreateStatic(&HandleExportMetadata),
		FParamSchemaBuilder()
			.Optional(TEXT("output_dir"), TEXT("string"), TEXT("Output directory under the project Saved directory"))
			.Optional(TEXT("include_objects"), TEXT("bool"), TEXT("Write per-actor object metadata"), TEXT("true"))
			.Optional(TEXT("include_foliage"), TEXT("bool"), TEXT("Include foliage-like actor classes"), TEXT("true"))
			.Optional(TEXT("max_actors"), TEXT("number"), TEXT("Maximum actors to include before reporting skipped rows"), TEXT("10000"))
			.Build());

	Registry.RegisterAction(TEXT("level"), TEXT("get_level_metadata"),
		TEXT("Return current editor level summary metadata without writing files."),
		FMonolithActionHandler::CreateStatic(&HandleGetLevelMetadata),
		FParamSchemaBuilder()
			.Optional(TEXT("include_foliage"), TEXT("bool"), TEXT("Include foliage-like actor classes"), TEXT("true"))
			.Optional(TEXT("max_actors"), TEXT("number"), TEXT("Maximum actors to include before reporting skipped rows"), TEXT("10000"))
			.Build());

	Registry.RegisterAction(TEXT("level"), TEXT("validate_metadata_export"),
		TEXT("Validate a Monolith level metadata export manifest and referenced files."),
		FMonolithActionHandler::CreateStatic(&HandleValidateMetadataExport),
		FParamSchemaBuilder()
			.Required(TEXT("manifest_path"), TEXT("string"), TEXT("Path to a manifest JSON generated by level.export_metadata"))
			.Build());
}

FMonolithEditorLevelMetadataActions::FExportOptions FMonolithEditorLevelMetadataActions::ParseOptions(const TSharedPtr<FJsonObject>& Params)
{
	FExportOptions Options;
	if (!Params.IsValid())
	{
		return Options;
	}

	Params->TryGetBoolField(TEXT("include_foliage"), Options.bIncludeFoliage);
	Params->TryGetBoolField(TEXT("include_objects"), Options.bIncludeObjects);
	Params->TryGetStringField(TEXT("output_dir"), Options.OutputDir);

	double MaxActors = static_cast<double>(Options.MaxActors);
	if (Params->TryGetNumberField(TEXT("max_actors"), MaxActors))
	{
		Options.MaxActors = FMath::Clamp(static_cast<int32>(MaxActors), 1, 100000);
	}

	return Options;
}

UWorld* FMonolithEditorLevelMetadataActions::GetEditorWorld()
{
	return GEditor ? GEditor->GetEditorWorldContext().World() : nullptr;
}

FMonolithActionResult FMonolithEditorLevelMetadataActions::HandlePreviewMetadataExport(const TSharedPtr<FJsonObject>& Params)
{
	FExportOptions Options = ParseOptions(Params);
	Options.bIncludeObjects = false;
	TSharedPtr<FJsonObject> Result = BuildLevelMetadata(Options, false);
	Result->SetBoolField(TEXT("preview_only"), true);
	Result->SetBoolField(TEXT("writes_files"), false);
	return FMonolithActionResult::Success(Result);
}

FMonolithActionResult FMonolithEditorLevelMetadataActions::HandleGetLevelMetadata(const TSharedPtr<FJsonObject>& Params)
{
	FExportOptions Options = ParseOptions(Params);
	Options.bIncludeObjects = false;
	return FMonolithActionResult::Success(BuildLevelMetadata(Options, false));
}

FMonolithActionResult FMonolithEditorLevelMetadataActions::HandleExportMetadata(const TSharedPtr<FJsonObject>& Params)
{
	FExportOptions Options = ParseOptions(Params);

	FString OutputDir;
	FString OutputError;
	if (!ResolveOutputDir(Options.OutputDir, OutputDir, OutputError))
	{
		return FMonolithActionResult::Error(OutputError);
	}

	TSharedPtr<FJsonObject> Metadata = BuildLevelMetadata(Options, Options.bIncludeObjects);
	FString SummaryJson;
	if (!JsonObjectToString(Metadata, SummaryJson))
	{
		return FMonolithActionResult::Error(TEXT("Failed to serialize level metadata"));
	}

	const FString LevelName = Metadata->GetStringField(TEXT("level_name"));
	const FString BaseName = MakeSafeBaseName(LevelName);
	const FString SummaryPath = FPaths::Combine(OutputDir, BaseName + TEXT("_meta.json"));
	const FString ActorsPath = FPaths::Combine(OutputDir, BaseName + TEXT("_actors.ndjson"));
	const FString ManifestPath = FPaths::Combine(OutputDir, BaseName + TEXT("_manifest.json"));

	if (!FFileHelper::SaveStringToFile(SummaryJson, *SummaryPath))
	{
		return FMonolithActionResult::Error(FString::Printf(TEXT("Failed to write metadata file: %s"), *SummaryPath));
	}

	TArray<TSharedPtr<FJsonValue>> Files;
	Files.Add(MakeShared<FJsonValueString>(SummaryPath));

	int32 ActorRowsWritten = 0;
	if (Options.bIncludeObjects)
	{
		const TArray<TSharedPtr<FJsonValue>>* ActorRows = nullptr;
		FString ActorNdjson;
		if (Metadata->TryGetArrayField(TEXT("actors"), ActorRows) && ActorRows)
		{
			for (const TSharedPtr<FJsonValue>& Row : *ActorRows)
			{
				FString RowJson;
				if (Row.IsValid() && Row->Type == EJson::Object && JsonObjectToString(Row->AsObject(), RowJson))
				{
					ActorNdjson += RowJson + LINE_TERMINATOR;
					++ActorRowsWritten;
				}
			}
		}

		if (!FFileHelper::SaveStringToFile(ActorNdjson, *ActorsPath))
		{
			return FMonolithActionResult::Error(FString::Printf(TEXT("Failed to write actor metadata file: %s"), *ActorsPath));
		}
		Files.Add(MakeShared<FJsonValueString>(ActorsPath));
	}

	TSharedPtr<FJsonObject> Manifest = MakeShared<FJsonObject>();
	Manifest->SetNumberField(TEXT("schema_version"), 1);
	Manifest->SetStringField(TEXT("kind"), TEXT("monolith_level_metadata_manifest"));
	Manifest->SetStringField(TEXT("level_name"), LevelName);
	Manifest->SetStringField(TEXT("summary_path"), SummaryPath);
	Manifest->SetStringField(TEXT("actors_path"), Options.bIncludeObjects ? ActorsPath : FString());
	Manifest->SetStringField(TEXT("summary_md5"), FMD5::HashAnsiString(*SummaryJson));
	Manifest->SetNumberField(TEXT("actor_rows_written"), ActorRowsWritten);
	Manifest->SetArrayField(TEXT("files"), Files);

	FString ManifestJson;
	if (!JsonObjectToString(Manifest, ManifestJson)
		|| !FFileHelper::SaveStringToFile(ManifestJson, *ManifestPath))
	{
		return FMonolithActionResult::Error(FString::Printf(TEXT("Failed to write manifest file: %s"), *ManifestPath));
	}

	TSharedPtr<FJsonObject> Result = MakeShared<FJsonObject>();
	Result->SetBoolField(TEXT("success"), true);
	Result->SetStringField(TEXT("output_dir"), OutputDir);
	Result->SetStringField(TEXT("summary_path"), SummaryPath);
	Result->SetStringField(TEXT("actors_path"), Options.bIncludeObjects ? ActorsPath : FString());
	Result->SetStringField(TEXT("manifest_path"), ManifestPath);
	Result->SetNumberField(TEXT("actor_rows_written"), ActorRowsWritten);
	Result->SetObjectField(TEXT("metadata"), Metadata);
	return FMonolithActionResult::Success(Result);
}

FMonolithActionResult FMonolithEditorLevelMetadataActions::HandleValidateMetadataExport(const TSharedPtr<FJsonObject>& Params)
{
	FString ManifestPath;
	if (!Params.IsValid() || !Params->TryGetStringField(TEXT("manifest_path"), ManifestPath) || ManifestPath.IsEmpty())
	{
		return FMonolithActionResult::Error(TEXT("manifest_path is required"));
	}

	FString ManifestJson;
	if (!FFileHelper::LoadFileToString(ManifestJson, *ManifestPath))
	{
		return FMonolithActionResult::Error(FString::Printf(TEXT("Failed to read manifest: %s"), *ManifestPath));
	}

	TSharedPtr<FJsonObject> Manifest;
	const TSharedRef<TJsonReader<>> Reader = TJsonReaderFactory<>::Create(ManifestJson);
	if (!FJsonSerializer::Deserialize(Reader, Manifest) || !Manifest.IsValid())
	{
		return FMonolithActionResult::Error(TEXT("Manifest is not valid JSON"));
	}

	TArray<TSharedPtr<FJsonValue>> MissingFiles;
	const TArray<TSharedPtr<FJsonValue>>* Files = nullptr;
	if (Manifest->TryGetArrayField(TEXT("files"), Files) && Files)
	{
		for (const TSharedPtr<FJsonValue>& FileValue : *Files)
		{
			FString FilePath;
			if (FileValue.IsValid() && FileValue->TryGetString(FilePath) && !FPaths::FileExists(FilePath))
			{
				MissingFiles.Add(MakeShared<FJsonValueString>(FilePath));
			}
		}
	}

	const bool bKindOk = Manifest->GetStringField(TEXT("kind")) == TEXT("monolith_level_metadata_manifest");
	TSharedPtr<FJsonObject> Result = MakeShared<FJsonObject>();
	Result->SetBoolField(TEXT("valid"), bKindOk && MissingFiles.Num() == 0);
	Result->SetBoolField(TEXT("kind_ok"), bKindOk);
	Result->SetNumberField(TEXT("missing_file_count"), MissingFiles.Num());
	Result->SetArrayField(TEXT("missing_files"), MissingFiles);
	Result->SetObjectField(TEXT("manifest"), Manifest);
	return FMonolithActionResult::Success(Result);
}

TSharedPtr<FJsonObject> FMonolithEditorLevelMetadataActions::BuildLevelMetadata(const FExportOptions& Options, bool bIncludeObjectRows)
{
	UWorld* World = GetEditorWorld();
	TSharedPtr<FJsonObject> Root = MakeShared<FJsonObject>();
	Root->SetNumberField(TEXT("schema_version"), 1);
	Root->SetStringField(TEXT("kind"), TEXT("monolith_level_metadata"));
	if (!World)
	{
		Root->SetStringField(TEXT("status"), TEXT("no_editor_world"));
		return Root;
	}

	const FString LevelName = World->GetMapName();
	Root->SetStringField(TEXT("status"), TEXT("ok"));
	Root->SetStringField(TEXT("level_name"), LevelName);
	Root->SetStringField(TEXT("map_package"), World->GetOutermost() ? World->GetOutermost()->GetName() : FString());
	Root->SetBoolField(TEXT("include_foliage"), Options.bIncludeFoliage);
	Root->SetNumberField(TEXT("max_actors"), Options.MaxActors);

	int32 SeenActors = 0;
	int32 IncludedActors = 0;
	int32 SkippedActors = 0;
	int32 LightActors = 0;
	int32 MeshActors = 0;
	int32 BlueprintActors = 0;
	int32 FoliageActors = 0;
	TSet<FString> UniqueMeshes;
	TSet<FString> UniqueMaterials;
	TSet<FString> Folders;
	TArray<TSharedPtr<FJsonValue>> ActorRows;
	TArray<TSharedPtr<FJsonValue>> Warnings;

	for (TActorIterator<AActor> It(World); It; ++It)
	{
		AActor* Actor = *It;
		if (!Actor)
		{
			continue;
		}

		++SeenActors;
		const bool bFoliageActor = IsFoliageActor(Actor);
		if (bFoliageActor)
		{
			++FoliageActors;
		}
		if (bFoliageActor && !Options.bIncludeFoliage)
		{
			++SkippedActors;
			continue;
		}
		if (IncludedActors >= Options.MaxActors)
		{
			++SkippedActors;
			continue;
		}

		if (Actor->IsA<ALight>())
		{
			++LightActors;
		}
		if (Actor->GetClass() && Actor->GetClass()->ClassGeneratedBy)
		{
			++BlueprintActors;
		}

		bool bHasMesh = false;
		TInlineComponentArray<UStaticMeshComponent*> MeshComponents(Actor);
		for (UStaticMeshComponent* MeshComponent : MeshComponents)
		{
			if (!MeshComponent)
			{
				continue;
			}
			if (UStaticMesh* Mesh = MeshComponent->GetStaticMesh())
			{
				bHasMesh = true;
				UniqueMeshes.Add(Mesh->GetPathName());
			}
			const int32 MaterialCount = MeshComponent->GetNumMaterials();
			for (int32 Index = 0; Index < MaterialCount; ++Index)
			{
				if (UMaterialInterface* Material = MeshComponent->GetMaterial(Index))
				{
					UniqueMaterials.Add(Material->GetPathName());
				}
			}
		}
		if (bHasMesh)
		{
			++MeshActors;
		}

		const FString FolderPath = Actor->GetFolderPath().ToString();
		if (!FolderPath.IsEmpty())
		{
			Folders.Add(FolderPath);
		}

		if (bIncludeObjectRows)
		{
			ActorRows.Add(MakeShared<FJsonValueObject>(ActorToMetadataJson(Actor)));
		}
		++IncludedActors;
	}

	if (SkippedActors > 0)
	{
		Warnings.Add(MakeShared<FJsonValueString>(FString::Printf(TEXT("%d actors skipped by filters or max_actors"), SkippedActors)));
	}

	Root->SetNumberField(TEXT("actor_count"), SeenActors);
	Root->SetNumberField(TEXT("included_actor_count"), IncludedActors);
	Root->SetNumberField(TEXT("skipped_actor_count"), SkippedActors);
	Root->SetNumberField(TEXT("light_count"), LightActors);
	Root->SetNumberField(TEXT("mesh_actor_count"), MeshActors);
	Root->SetNumberField(TEXT("blueprint_actor_count"), BlueprintActors);
	Root->SetNumberField(TEXT("foliage_actor_count"), FoliageActors);
	Root->SetNumberField(TEXT("unique_mesh_count"), UniqueMeshes.Num());
	Root->SetNumberField(TEXT("unique_material_count"), UniqueMaterials.Num());
	MonolithLevelMetadata::AddStringSetAsArray(Root, TEXT("folders"), Folders);
	MonolithLevelMetadata::AddStringSetAsArray(Root, TEXT("unique_meshes"), UniqueMeshes);
	MonolithLevelMetadata::AddStringSetAsArray(Root, TEXT("unique_materials"), UniqueMaterials);
	Root->SetArrayField(TEXT("warnings"), Warnings);
	if (bIncludeObjectRows)
	{
		Root->SetArrayField(TEXT("actors"), ActorRows);
	}
	return Root;
}

TSharedPtr<FJsonObject> FMonolithEditorLevelMetadataActions::ActorToMetadataJson(AActor* Actor)
{
	TSharedPtr<FJsonObject> Obj = MakeShared<FJsonObject>();
	if (!Actor)
	{
		return Obj;
	}

	Obj->SetStringField(TEXT("label"), Actor->GetActorLabel());
	Obj->SetStringField(TEXT("name"), Actor->GetName());
	Obj->SetStringField(TEXT("object_path"), Actor->GetPathName());
	Obj->SetStringField(TEXT("class"), Actor->GetClass() ? Actor->GetClass()->GetName() : FString());
	Obj->SetStringField(TEXT("class_path"), Actor->GetClass() ? Actor->GetClass()->GetClassPathName().ToString() : FString());
	Obj->SetStringField(TEXT("folder"), Actor->GetFolderPath().ToString());
	Obj->SetObjectField(TEXT("transform"), MonolithLevelMetadata::TransformToJson(Actor->GetActorTransform()));
	Obj->SetBoolField(TEXT("is_light"), Actor->IsA<ALight>());
	Obj->SetBoolField(TEXT("is_blueprint_actor"), Actor->GetClass() && Actor->GetClass()->ClassGeneratedBy != nullptr);
	Obj->SetBoolField(TEXT("is_foliage_actor"), IsFoliageActor(Actor));

	TArray<TSharedPtr<FJsonValue>> Meshes;
	TArray<TSharedPtr<FJsonValue>> Materials;
	TInlineComponentArray<UStaticMeshComponent*> MeshComponents(Actor);
	for (UStaticMeshComponent* MeshComponent : MeshComponents)
	{
		if (!MeshComponent)
		{
			continue;
		}
		if (UStaticMesh* Mesh = MeshComponent->GetStaticMesh())
		{
			Meshes.Add(MakeShared<FJsonValueString>(Mesh->GetPathName()));
		}
		for (int32 Index = 0; Index < MeshComponent->GetNumMaterials(); ++Index)
		{
			if (UMaterialInterface* Material = MeshComponent->GetMaterial(Index))
			{
				Materials.Add(MakeShared<FJsonValueString>(Material->GetPathName()));
			}
		}
	}
	Obj->SetArrayField(TEXT("static_meshes"), Meshes);
	Obj->SetArrayField(TEXT("materials"), Materials);
	return Obj;
}

bool FMonolithEditorLevelMetadataActions::IsFoliageActor(const AActor* Actor)
{
	return Actor && Actor->GetClass()
		&& Actor->GetClass()->GetName().Contains(TEXT("Foliage"), ESearchCase::IgnoreCase);
}

bool FMonolithEditorLevelMetadataActions::ResolveOutputDir(const FString& RequestedDir, FString& OutDir, FString& OutError)
{
	const FString SavedRoot = FPaths::ConvertRelativePathToFull(FPaths::ProjectSavedDir());
	OutDir = RequestedDir.IsEmpty()
		? FPaths::Combine(SavedRoot, TEXT("Monolith"), TEXT("LevelMetadata"))
		: RequestedDir;
	if (FPaths::IsRelative(OutDir))
	{
		OutDir = FPaths::Combine(SavedRoot, OutDir);
	}
	OutDir = FPaths::ConvertRelativePathToFull(OutDir);
	FPaths::NormalizeDirectoryName(OutDir);

	FString NormalizedSavedRoot = SavedRoot;
	FPaths::NormalizeDirectoryName(NormalizedSavedRoot);
	if (!OutDir.StartsWith(NormalizedSavedRoot))
	{
		OutError = FString::Printf(TEXT("output_dir must resolve under ProjectSavedDir: %s"), *NormalizedSavedRoot);
		return false;
	}

	if (!IFileManager::Get().MakeDirectory(*OutDir, true))
	{
		OutError = FString::Printf(TEXT("Failed to create output_dir: %s"), *OutDir);
		return false;
	}
	return true;
}

bool FMonolithEditorLevelMetadataActions::JsonObjectToString(const TSharedPtr<FJsonObject>& Object, FString& OutJson)
{
	if (!Object.IsValid())
	{
		return false;
	}

	const TSharedRef<TJsonWriter<>> Writer = TJsonWriterFactory<>::Create(&OutJson);
	return FJsonSerializer::Serialize(Object.ToSharedRef(), Writer);
}

FString FMonolithEditorLevelMetadataActions::MakeSafeBaseName(const FString& LevelName)
{
	const FString Base = LevelName.IsEmpty() ? TEXT("Level") : LevelName;
	return FPaths::MakeValidFileName(Base);
}
